// <auto-generated />
using Car.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Car.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240925040128_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Car.Entities.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Carss");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "White",
                            Manufacturer = "Chevrolet",
                            Model = "Cobalt",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Malibu",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green",
                            Manufacturer = "Toyota",
                            Model = "Camry",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 4,
                            Color = "Red",
                            Manufacturer = "Honda",
                            Model = "Civic",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 5,
                            Color = "Yellow",
                            Manufacturer = "Ford",
                            Model = "Focus",
                            Price = 7000m
                        },
                        new
                        {
                            Id = 6,
                            Color = "Black",
                            Manufacturer = "BMW",
                            Model = "X5",
                            Price = 20000m
                        },
                        new
                        {
                            Id = 7,
                            Color = "Blue",
                            Manufacturer = "Audi",
                            Model = "A4",
                            Price = 9000m
                        },
                        new
                        {
                            Id = 8,
                            Color = "Black",
                            Manufacturer = "Mercedes",
                            Model = "C-Class",
                            Price = 18000m
                        },
                        new
                        {
                            Id = 9,
                            Color = "White",
                            Manufacturer = "Hyundai",
                            Model = "Elantra",
                            Price = 11000m
                        },
                        new
                        {
                            Id = 10,
                            Color = "Green",
                            Manufacturer = "Kia",
                            Model = "Optima",
                            Price = 6000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
